version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: aslam
      MONGO_INITDB_ROOT_PASSWORD: aslam_pass
    networks:
      api_net:
        ipv4_address: 10.5.0.3


  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aslam
      ME_CONFIG_MONGODB_ADMINPASSWORD: aslam_pass
      ME_CONFIG_MONGODB_URL: mongodb://aslam:aslam_pass@10.5.0.3:27017/
    networks:
      api_net:
        ipv4_address: 10.5.0.4

networks:
  api_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
